package eu.auctionplatform.auction.domain.model

import eu.auctionplatform.commons.domain.BidId
import eu.auctionplatform.commons.domain.Money
import eu.auctionplatform.commons.domain.UserId
import java.time.Instant

/**
 * Immutable value object representing a single bid in an auction.
 *
 * A bid is identified by its [id] and belongs to a specific [bidderId]. The [amount]
 * represents the monetary value of the bid. Bids may originate from direct user
 * action or from the automatic proxy-bidding system (indicated by [isProxy]).
 *
 * The [status] tracks the bid's lifecycle within the auction:
 * - [BidStatus.ACTIVE] upon initial placement
 * - [BidStatus.OUTBID] when a higher bid is placed
 * - [BidStatus.WINNING] when the auction closes and this is the highest bid
 * - [BidStatus.REJECTED] if the bid fails validation
 *
 * @property id Unique identifier for this bid (UUIDv7).
 * @property bidderId Identifier of the user who placed (or on whose behalf) the bid.
 * @property amount Monetary value of the bid.
 * @property timestamp UTC instant when the bid was placed.
 * @property isProxy `true` if this bid was automatically generated by the proxy-bid engine.
 * @property status Current lifecycle status of the bid.
 */
data class Bid(
    val id: BidId,
    val bidderId: UserId,
    val amount: Money,
    val timestamp: Instant,
    val isProxy: Boolean,
    val status: BidStatus
) {

    /**
     * Returns a copy of this bid with the given [newStatus].
     */
    fun withStatus(newStatus: BidStatus): Bid = copy(status = newStatus)

    /**
     * Returns `true` if this bid is currently the leading bid (ACTIVE and not outbid).
     */
    fun isLeading(): Boolean = status == BidStatus.ACTIVE

    /**
     * Returns `true` if this bid has been surpassed by a higher bid.
     */
    fun isOutbid(): Boolean = status == BidStatus.OUTBID
}
